### PR TITLE
Major render modifications

### PR DESCRIPTION
**Pull request by matthewd673**
Rewriting the renderer to be more efficient (and hopefully flash less, see issue #8 ).

### CODE REVIEW

**Comment by matthewd673** [comment]
Going to recreate the branch so its up to date

**Comment by matthewd673** [comment]
Done, next build shouldn't fail & I can get back to work

**Comment by matthewd673** [comment]
Says that some checks were not successful but I just rebuilt on veyor with no problem. Next commit it'll probably straighten itself out.

**Comment by DontBelieveMe** [comment]
Persistence is key...

**Comment by matthewd673** [comment]
No conflicts from github, hopefully the veyor build will pass painlessly

**Comment by matthewd673** [comment]
This is getting out of hand, all commits are going directly to master to avoid conflicts

**Pull request closed without merging**
