### PR TITLE
Math + Vector2 added

### PR DESCRIPTION
**Pull request by matthewd673**

### CODE REVIEW

**Comment by matthewd673** [comment]
Is this what you were looking for, @DontBelieveMe or should I change it before merging?

**Comment by DontBelieveMe** [comment]
I would use a class as opposed to a struct - purely for the reason that it is handy for vectors to have constructors. Also why expose private `_x`and `_y`using `get`and `set`and not just make them public?

**Comment by DontBelieveMe** [comment]
If you like I can quickly whip up a small math library, and then I'll look at the renderer stuff?

**Comment by matthewd673** [comment]
Sounds good. I got a start on it already, so just go from there with structs and we'll be done in no time :smile: I created branch new-renderer-#9 for renderer stuff & I'll be pushing to that regularly in the coming hours.

**Comment by DontBelieveMe** [comment]
I have got the basics for this up and running on a local branch, so tomorrow I'll clean it up, create a PR and if it's accepted I'll do the docs.

**Comment by matthewd673** [comment]
Alright. I'll be focusing on the renderer for the next few days, but after that comes a fun part: particles! Can't wait to work on it

**Pull request merged**
